---
pcs01:
  memory: 512
  cpus: 1
  address: 192.168.33.10
  box: RH7.1

#pcs02:
#  memory: 512
#  cpus: 1
#  address: 192.168.33.11
#  box: RH7.1

#pcs03:
#  memory: 512
#  cpus: 1
#  address: 192.168.33.12
#  box: RH7.1
