---
## RHEL 7 Local repo -- Testing purposes (Erasable) --
  - name: clean repos
    command: rm -f /etc/yum.repos.d/*.repo

  - name: Pacemaker Local Repo
    template: src=repository.j2
              dest=/etc/yum.repos.d/{{ item.name }}.repo
              owner=root
              group=root
              mode=0644
    with_items:
      - { name: pcs_local, baseurl: "{{ pacemaker_repo }}" }
    when: ansible_distribution_major_version == '7'
    notify:
      - clean packages

  - meta: flush_handlers

  # Install PCS stuff
  - name: Install Pacemaker
    yum: pkg={{item}} state=latest
    with_items:
      - pcs
      - pacemaker
      - corosync
      - fence-agents-all
      - resource-agents
      - openstack-selinux
    notify:
      - Manage Service pcsd
      - Manage Service firewalld

  - meta: flush_handlers

  - name: Get Firewalld services
    command: firewall-cmd --list-services
    register: service

  - name: Change hacluster pass
    user: name=hacluster password={{cluster_pass_cyph}}

  - name: Firewalld HA Allow
    command: firewall-cmd --permanent --add-service=high-availability
    when: "'high-availability' not in service.stdout"
    notify:
      - firewall-reload

  - meta: flush_handlers

  ## This function will add all nodes from group['name'] to hosts file
  ## into the guest clients, change ansible_default_ipv4 for the needed inteface
  ## ansible_eth1.ipv4.address
  - name: Build hosts file
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item]['ansible_hostname'] }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['vagrant']
